### ISSUE TITLE
[bal-hint] When the user uses mobile view and opens a pop-up module, after closing content disappears.

### ISSUE THREAD

**Issue by dstab** [baloise-incubator/design-system#599] opened 2022-09-21 10:22 UTC
## Detailed description
When the user uses mobile view and clicks on an extra information option that opens a pop-up module, and then closes it,
Then all apps content disappears. Also, not possible to see the previous content via the back button. 
`bal-hint` component is being used to trigger the popup. Once triggered and closed it doesn't return previous screen back to normal.

https://user-images.githubusercontent.com/107861285/191480571-5c894f75-e041-4105-b8e6-46185c34791e.mov

**Comment by Gagne87** [comment] 2022-09-22 08:37
I just tried to reproduce on my Mobile (iPhone 12 mini, iOS 16.0, Safari) with following outcome: 

- Kasko object insurance: Could reproduce
- Storybook: Could not reproduce

@joachimprinzbach how should we proceed with that one?

**Comment by joachimprinzbach** [comment] 2022-09-22 09:24
imo has to be fixed by Kasko then, sounds like an application specific problem

**Comment by hirsch88** [comment] 2022-09-28 12:55
@Gagne87 could you check the state with them

**Comment by clastzoo** [comment] 2022-09-29 08:08
@Gagne87 will contact kasko since the issue is on their side

**Comment by dstab** [comment] 2022-09-29 10:34
Hi, @Gagne87 

This seems to have resolved itself. We are not quite sure what caused this. This might get fixed with your latest bugfixes or might be fixed by our bug fixes. Nevertheless, it seems that no one did try to intentionally resolve this. 

Best regards
dstab

**Closed as completed** 2022-09-30 12:25 UTC
Labels: 🐛 Bug, 🧑‍💻 Technical Design System, 💅 Style Issue
