### ISSUE TITLE
[bal-list-item] with accordion="true": accordion with image not showing full height of image

### ISSUE THREAD

**Issue by Sreilys** [baloise-incubator/design-system#683] opened 2022-10-05 09:44 UTC
## Detailed description

> When using bal-list-item with the option of accordion setted to true and having an image as accordion body, the bal-list-item-accordion-body gets at first a style of max-height: 104px; (bug). But, when we close and reopen the accordion, the max-heigh is right, and the image inside is showed correctly. 

> What did you expect to happen? What happened instead? What would you like to see changed?
Height of the bal-list-item-accordion-body is always consistent.

> What browser are you working in?
Chrome, Firefox

## Steps to reproduce the issue
Use an image as content of a bal-list-item with the accordion prop = true

## Additional information

<img width="1711" alt="Screenshot 2022-10-05 at 11 29 25" src="https://user-images.githubusercontent.com/8192292/194031454-553e0e00-113a-4215-956d-4379920175ba.png">

**Comment by Gagne87** [comment] 2022-10-06 08:14
@Sreilys also for here: Can you please add a concrete use-case? Is this really used on the website? How relevant is it? Thanks for your answer.

**Comment by madaluca** [comment] 2022-10-06 09:07
@Gagne87 , the problem is that the image is lazy loaded in our side, so it is loaded when the accordion is opened for the first time. Maybe we can close this issue and let's hope https://github.com/baloise-incubator/design-system/issues/672 we'll be a solution also for this issue

**Comment by madaluca** [comment] 2022-10-06 15:36
@Mladen, we can fix the issue on our side, as we've discussed before, so you can close the issue. Thanks

**Closed as completed** 2022-10-07 08:02 UTC
Labels: 🐛 Bug
